<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Aaru.CommonTypes"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies"/>
    <PackageReference Include="Microsoft.Extensions.Configuration"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql"/>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design"/>
  </ItemGroup>
</Project>
