<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>aspnet-Aaru.Server-79282495-4F67-4766-871D-448D1338E8BC</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aaru.CommonTypes"/>
    <PackageReference Include="Aaru.Decoders"/>
    <PackageReference Include="Aaru.Dto"/>
    <PackageReference Include="Blazor.Bootstrap"/>
    <PackageReference Include="HtmlAgilityPack"/>
    <PackageReference Include="ChoPGP"/>
    <PackageReference Include="MailKit"/>
    <PackageReference Include="Markdig"/>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"/>
    <PackageReference Include="MimeKit"/>
    <PackageReference Include="WebStoating.Markdig.PrismWithPlugins"/>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql"/>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies"/>
    <PackageReference Include="AsyncFixer"/>
    <PackageReference Include="ErrorProne.NET.CoreAnalyzers"/>
    <PackageReference Include="ErrorProne.NET.Structs"/>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers"/>
    <PackageReference Include="Philips.CodeAnalysis.MaintainabilityAnalyzers"/>
    <PackageReference Include="Roslynator.Analyzers"/>
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers"/>
    <PackageReference Include="Roslynator.Formatting.Analyzers"/>
    <PackageReference Include="SmartAnalyzers.MultithreadingAnalyzer"/>
    <PackageReference Include="Text.Analyzers"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\assets\"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Aaru.Documentation\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aaru.Server.Database\Aaru.Server.Database.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\..\.nuget\packages\newtonsoft.json\13.0.1\lib\netstandard2.0\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="drive_offsets.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
