// <auto-generated />
using System;
using Aaru.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aaru.Server.Migrations
{
    [DbContext(typeof(DicServerContext))]
    [Migration("20191204182314_RemoteStatistics")]
    partial class RemoteStatistics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Ata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Identify")
                        .HasColumnType("longblob");

                    b.Property<int?>("ReadCapabilitiesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReadCapabilitiesId");

                    b.ToTable("Ata");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.BlockDescriptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<uint?>("BlockLength")
                        .HasColumnType("int unsigned");

                    b.Property<ulong?>("Blocks")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("Density")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("ScsiModeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScsiModeId");

                    b.ToTable("BlockDescriptor");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Chs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ushort>("Cylinders")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Heads")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Sectors")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Chs");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.DensityCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int?>("SscSupportedMediaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SscSupportedMediaId");

                    b.ToTable("DensityCode");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.FireWire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Product")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<uint>("ProductID")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("RemovableMedia")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("VendorID")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("FireWire");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Mmc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FeaturesId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ModeSense2AData")
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("FeaturesId");

                    b.ToTable("Mmc");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.MmcFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte?>("AACSVersion")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("AGIDs")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte[]>("BinaryData")
                        .HasColumnType("longblob");

                    b.Property<byte?>("BindingNonceBlocks")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ushort?>("BlocksPerReadableUnit")
                        .HasColumnType("smallint unsigned");

                    b.Property<bool>("BufferUnderrunFreeInDVD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BufferUnderrunFreeInSAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BufferUnderrunFreeInTAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("CPRMVersion")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("CSSVersion")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("CanAudioScan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanEject")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanEraseSector")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanExpandBDRESpareArea")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanFormat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanFormatBDREWithoutSpare")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanFormatCert")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanFormatFRF")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanFormatQCert")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanFormatRRM")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanGenerateBindingNonce")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanLoad")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanMuteSeparateChannels")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanOverwriteSAOTrack")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanOverwriteTAOTrack")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanPlayCDAudio")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanPseudoOverwriteBDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadAllDualR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadAllDualRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadBD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadBDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadBDRE1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadBDRE2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadBDROM")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadBluBCA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadCD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadCDMRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadCPRM_MKB")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadDDCD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadDVD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadDVDPlusMRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadDVDPlusR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadDVDPlusRDL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadDVDPlusRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadDVDPlusRWDL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadDriveAACSCertificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadHDDVD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadHDDVDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadHDDVDRAM")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadLeadInCDText")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadOldBDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadOldBDRE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadOldBDROM")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReadSpareAreaInformation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReportDriveSerial")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReportMediaSerial")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanTestWriteDDCDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanTestWriteDVD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanTestWriteInSAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanTestWriteInTAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanUpgradeFirmware")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteBD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteBDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteBDRE1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteBDRE2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteBusEncryptedBlocks")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteCDMRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteCDRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteCDRWCAV")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteCDSAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteCDTAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteCSSManagedDVD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDDCDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDDCDRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDVDPlusMRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDVDPlusR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDVDPlusRDL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDVDPlusRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDVDPlusRWDL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDVDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDVDRDL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteDVDRW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteHDDVDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteHDDVDRAM")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteOldBDR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteOldBDRE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWritePackedSubchannelInTAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteRWSubchannelInSAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteRWSubchannelInTAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteRaw")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteRawMultiSession")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanWriteRawSubchannelInTAO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ChangerIsSideChangeCapable")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("ChangerSlots")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("ChangerSupportsDiscPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DBML")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DVDMultiRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EmbeddedChanger")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ErrorRecoveryPage")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FirmwareDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte?>("LoadingMechanismType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("LogicalBlockSize")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("MultiRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("PhysicalInterfaceStandardNumber")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("PreventJumper")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsAACS")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsBusEncryption")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsC2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsCPRM")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsCSS")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsDAP")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsDeviceBusyEvent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsHybridDiscs")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsModePage1Ch")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsOSSC")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsPWP")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsSWPP")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsSecurDisc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsSeparateVolume")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsVCPS")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsWriteInhibitDCB")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsWriteProtectPAC")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort?>("VolumeLevels")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("MmcFeatures");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.MmcSd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("CID")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("CSD")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ExtendedCSD")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("OCR")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("SCR")
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.ToTable("MmcSd");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Pcmcia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("CIS")
                        .HasColumnType("longblob");

                    b.Property<ushort?>("CardCode")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Compliance")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<ushort?>("ManufacturerCode")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Pcmcia");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Scsi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("InquiryData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ModeSense10ChangeableData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ModeSense10CurrentData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ModeSense10Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ModeSense6ChangeableData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ModeSense6CurrentData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ModeSense6Data")
                        .HasColumnType("longblob");

                    b.Property<int?>("ModeSenseId")
                        .HasColumnType("int");

                    b.Property<int?>("MultiMediaDeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("ReadCapabilitiesId")
                        .HasColumnType("int");

                    b.Property<int?>("SequentialDeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("SupportsModeSense10")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsModeSense6")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsModeSubpages")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ModeSenseId");

                    b.HasIndex("MultiMediaDeviceId");

                    b.HasIndex("ReadCapabilitiesId");

                    b.HasIndex("SequentialDeviceId");

                    b.ToTable("Scsi");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.ScsiMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("BlankCheckEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("BufferedMode")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("DPOandFUA")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("MediumType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("Speed")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("WriteProtected")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ScsiMode");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.ScsiPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ScsiId")
                        .HasColumnType("int");

                    b.Property<int?>("ScsiModeId")
                        .HasColumnType("int");

                    b.Property<byte>("page")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("subpage")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte[]>("value")
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("ScsiId");

                    b.HasIndex("ScsiModeId");

                    b.ToTable("ScsiPage");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Ssc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte?>("BlockSizeGranularity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint?>("MaxBlockLength")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("MinBlockLength")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("Ssc");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.SscSupportedMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<ushort>("Length")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte>("MediumType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Organization")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SscId")
                        .HasColumnType("int");

                    b.Property<int?>("TestedSequentialMediaId")
                        .HasColumnType("int");

                    b.Property<ushort>("Width")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("SscId");

                    b.HasIndex("TestedSequentialMediaId");

                    b.ToTable("SscSupportedMedia");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.SupportedDensity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<uint>("BitsPerMm")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Capacity")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("DefaultDensity")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Duplicate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Organization")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte>("PrimaryCode")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("SecondaryCode")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("SscId")
                        .HasColumnType("int");

                    b.Property<int?>("TestedSequentialMediaId")
                        .HasColumnType("int");

                    b.Property<ushort>("Tracks")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Width")
                        .HasColumnType("smallint unsigned");

                    b.Property<bool>("Writable")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SscId");

                    b.HasIndex("TestedSequentialMediaId");

                    b.ToTable("SupportedDensity");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.TestedMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("AdipData")
                        .HasColumnType("longblob");

                    b.Property<int?>("AtaId")
                        .HasColumnType("int");

                    b.Property<byte[]>("AtipData")
                        .HasColumnType("longblob");

                    b.Property<uint?>("BlockSize")
                        .HasColumnType("int unsigned");

                    b.Property<ulong?>("Blocks")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte[]>("BluBcaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("BluDdsData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("BluDiData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("BluPacData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("BluSaiData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("C2PointersData")
                        .HasColumnType("longblob");

                    b.Property<int?>("CHSId")
                        .HasColumnType("int");

                    b.Property<bool?>("CanReadAACS")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadADIP")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadATIP")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadBCA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadC2Pointers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadCMI")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadCdScrambled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadCorrectedSubchannel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadCorrectedSubchannelWithC2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadDCB")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadDDS")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadDMI")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadDiscInformation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadFirstTrackPreGap")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadFullTOC")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadHDCMI")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadLayerCapacity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadLeadIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadLeadOut")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadMediaID")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadMediaSerial")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadPAC")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadPFI")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadPMA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadPQSubchannel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadPQSubchannelWithC2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadPRI")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadRWSubchannel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadRWSubchannelWithC2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadRecordablePFI")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadSpareAreaInformation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadTOC")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadingIntersessionLeadIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadingIntersessionLeadOut")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("CmiData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("CorrectedSubchannelData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("CorrectedSubchannelWithC2Data")
                        .HasColumnType("longblob");

                    b.Property<int?>("CurrentCHSId")
                        .HasColumnType("int");

                    b.Property<byte[]>("DcbData")
                        .HasColumnType("longblob");

                    b.Property<byte?>("Density")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte[]>("DmiData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("DvdAacsData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("DvdBcaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("DvdDdsData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("DvdLayerData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("DvdSaiData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("EmbossedPfiData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("FullTocData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("HLDTSTReadRawDVDData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("HdCmiData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("IdentifyData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("IntersessionLeadInData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("IntersessionLeadOutData")
                        .HasColumnType("longblob");

                    b.Property<ulong?>("LBA48Sectors")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint?>("LBASectors")
                        .HasColumnType("int unsigned");

                    b.Property<byte[]>("LeadInData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("LeadOutData")
                        .HasColumnType("longblob");

                    b.Property<ushort?>("LogicalAlignment")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint?>("LongBlockSize")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("MediaIsRecognized")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("MediumType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("MediumTypeName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("MmcId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ModeSense10Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ModeSense6Data")
                        .HasColumnType("longblob");

                    b.Property<string>("Model")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("NecReadCddaData")
                        .HasColumnType("longblob");

                    b.Property<ushort?>("NominalRotationRate")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte[]>("PQSubchannelData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PQSubchannelWithC2Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PfiData")
                        .HasColumnType("longblob");

                    b.Property<uint?>("PhysicalBlockSize")
                        .HasColumnType("int unsigned");

                    b.Property<byte[]>("PioneerReadCddaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PioneerReadCddaMsfData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PlextorReadCddaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PlextorReadRawDVDData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PmaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PriData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("RWSubchannelData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("RWSubchannelWithC2Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Read10Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Read12Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Read16Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Read6Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadCdData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadCdFullData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadCdMsfData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadCdMsfFullData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadCdScrambledData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadDmaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadDmaLba48Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadDmaLbaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadDmaRetryData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadDmaRetryLbaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadLba48Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadLbaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadLong10Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadLong16Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadLongData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadLongLbaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadLongRetryData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadLongRetryLbaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadRetryLbaData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadSectorsData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ReadSectorsRetryData")
                        .HasColumnType("longblob");

                    b.Property<int?>("ScsiId")
                        .HasColumnType("int");

                    b.Property<bool?>("SolidStateDevice")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsHLDTSTReadRawDVD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsNECReadCDDA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsPioneerReadCDDA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsPioneerReadCDDAMSF")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsPlextorReadCDDA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsPlextorReadRawDVD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsRead10")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsRead12")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsRead16")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsRead6")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadCapacity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadCapacity16")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadCd")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadCdMsf")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadCdMsfRaw")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadCdRaw")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadDma")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadDmaLba")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadDmaLba48")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadDmaRetry")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadDmaRetryLba")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadLba")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadLba48")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadLong")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadLong16")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadLongLba")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadLongRetry")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadLongRetryLba")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadRetry")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadRetryLba")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsReadSectors")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsSeek")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SupportsSeekLba")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("TocData")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Track1PregapData")
                        .HasColumnType("longblob");

                    b.Property<ushort?>("UnformattedBPS")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("UnformattedBPT")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AtaId");

                    b.HasIndex("CHSId");

                    b.HasIndex("CurrentCHSId");

                    b.HasIndex("MmcId");

                    b.HasIndex("ScsiId");

                    b.ToTable("TestedMedia");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.TestedSequentialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("CanReadMediaSerial")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("Density")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("MediaIsRecognized")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("MediumType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("MediumTypeName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("ModeSense10Data")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ModeSense6Data")
                        .HasColumnType("longblob");

                    b.Property<string>("Model")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SscId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SscId");

                    b.ToTable("TestedSequentialMedia");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Usb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Descriptors")
                        .HasColumnType("longblob");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Product")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<ushort>("ProductID")
                        .HasColumnType("smallint unsigned");

                    b.Property<bool>("RemovableMedia")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("VendorID")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Usb");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.CompactDiscOffset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedWhen")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Agreement")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Model")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifiedWhen")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Offset")
                        .HasColumnType("smallint");

                    b.Property<int>("Submissions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedWhen");

                    b.ToTable("CdOffsets");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ATAId")
                        .HasColumnType("int");

                    b.Property<int?>("ATAPIId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedWhen")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CdOffsetId")
                        .HasColumnType("int");

                    b.Property<bool>("CompactFlash")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("FireWireId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Model")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedWhen")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MultiMediaCardId")
                        .HasColumnType("int");

                    b.Property<int>("OptimalMultipleSectorsRead")
                        .HasColumnType("int");

                    b.Property<int?>("PCMCIAId")
                        .HasColumnType("int");

                    b.Property<string>("Revision")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SCSIId")
                        .HasColumnType("int");

                    b.Property<int?>("SecureDigitalId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("USBId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ATAId");

                    b.HasIndex("ATAPIId");

                    b.HasIndex("CdOffsetId");

                    b.HasIndex("FireWireId");

                    b.HasIndex("ModifiedWhen");

                    b.HasIndex("MultiMediaCardId");

                    b.HasIndex("PCMCIAId");

                    b.HasIndex("SCSIId");

                    b.HasIndex("SecureDigitalId");

                    b.HasIndex("USBId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.DeviceStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bus")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Model")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Revision")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("DeviceStats");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.Filesystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Filesystems");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.Filter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<bool>("Real")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.MediaFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("MediaFormats");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.OperatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Version")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.Partition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Partitions");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.RemoteApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Version")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("RemoteApplications");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.RemoteArchitecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("RemoteArchitectures");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.RemoteOperatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Version")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("RemoteOperatingSystems");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.UploadedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ATAId")
                        .HasColumnType("int");

                    b.Property<int?>("ATAPIId")
                        .HasColumnType("int");

                    b.Property<bool>("CompactFlash")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("FireWireId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Model")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("MultiMediaCardId")
                        .HasColumnType("int");

                    b.Property<int?>("PCMCIAId")
                        .HasColumnType("int");

                    b.Property<string>("Revision")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SCSIId")
                        .HasColumnType("int");

                    b.Property<int?>("SecureDigitalId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("USBId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedWhen")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ATAId");

                    b.HasIndex("ATAPIId");

                    b.HasIndex("FireWireId");

                    b.HasIndex("MultiMediaCardId");

                    b.HasIndex("PCMCIAId");

                    b.HasIndex("SCSIId");

                    b.HasIndex("SecureDigitalId");

                    b.HasIndex("USBId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.UsbProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedWhen")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedWhen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Product")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<ushort>("ProductId")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedWhen");

                    b.HasIndex("ProductId");

                    b.HasIndex("VendorId");

                    b.ToTable("UsbProducts");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.UsbVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedWhen")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedWhen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Vendor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<ushort>("VendorId")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedWhen");

                    b.HasIndex("VendorId")
                        .IsUnique();

                    b.ToTable("UsbVendors");
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Ata", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.TestedMedia", "ReadCapabilities")
                        .WithMany()
                        .HasForeignKey("ReadCapabilitiesId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.BlockDescriptor", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.ScsiMode", null)
                        .WithMany("BlockDescriptors")
                        .HasForeignKey("ScsiModeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.DensityCode", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.SscSupportedMedia", null)
                        .WithMany("DensityCodes")
                        .HasForeignKey("SscSupportedMediaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Mmc", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.MmcFeatures", "Features")
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.Scsi", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.ScsiMode", "ModeSense")
                        .WithMany()
                        .HasForeignKey("ModeSenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Mmc", "MultiMediaDevice")
                        .WithMany()
                        .HasForeignKey("MultiMediaDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.TestedMedia", "ReadCapabilities")
                        .WithMany()
                        .HasForeignKey("ReadCapabilitiesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Ssc", "SequentialDevice")
                        .WithMany()
                        .HasForeignKey("SequentialDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.ScsiPage", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Scsi", null)
                        .WithMany("EVPDPages")
                        .HasForeignKey("ScsiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.ScsiMode", null)
                        .WithMany("ModePages")
                        .HasForeignKey("ScsiModeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.SscSupportedMedia", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Ssc", null)
                        .WithMany("SupportedMediaTypes")
                        .HasForeignKey("SscId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.TestedSequentialMedia", null)
                        .WithMany("SupportedMediaTypes")
                        .HasForeignKey("TestedSequentialMediaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.SupportedDensity", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Ssc", null)
                        .WithMany("SupportedDensities")
                        .HasForeignKey("SscId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.TestedSequentialMedia", null)
                        .WithMany("SupportedDensities")
                        .HasForeignKey("TestedSequentialMediaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.TestedMedia", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Ata", null)
                        .WithMany("RemovableMedias")
                        .HasForeignKey("AtaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Chs", "CHS")
                        .WithMany()
                        .HasForeignKey("CHSId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Chs", "CurrentCHS")
                        .WithMany()
                        .HasForeignKey("CurrentCHSId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Mmc", null)
                        .WithMany("TestedMedia")
                        .HasForeignKey("MmcId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Scsi", null)
                        .WithMany("RemovableMedias")
                        .HasForeignKey("ScsiId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.CommonTypes.Metadata.TestedSequentialMedia", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Ssc", null)
                        .WithMany("TestedMedia")
                        .HasForeignKey("SscId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.Device", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Ata", "ATA")
                        .WithMany()
                        .HasForeignKey("ATAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Ata", "ATAPI")
                        .WithMany()
                        .HasForeignKey("ATAPIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.Server.Models.CompactDiscOffset", "CdOffset")
                        .WithMany("Devices")
                        .HasForeignKey("CdOffsetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.FireWire", "FireWire")
                        .WithMany()
                        .HasForeignKey("FireWireId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.MmcSd", "MultiMediaCard")
                        .WithMany()
                        .HasForeignKey("MultiMediaCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Pcmcia", "PCMCIA")
                        .WithMany()
                        .HasForeignKey("PCMCIAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Scsi", "SCSI")
                        .WithMany()
                        .HasForeignKey("SCSIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.MmcSd", "SecureDigital")
                        .WithMany()
                        .HasForeignKey("SecureDigitalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Usb", "USB")
                        .WithMany()
                        .HasForeignKey("USBId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.DeviceStat", b =>
                {
                    b.HasOne("DiscImageChef.Server.Models.Device", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.UploadedReport", b =>
                {
                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Ata", "ATA")
                        .WithMany()
                        .HasForeignKey("ATAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Ata", "ATAPI")
                        .WithMany()
                        .HasForeignKey("ATAPIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.FireWire", "FireWire")
                        .WithMany()
                        .HasForeignKey("FireWireId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.MmcSd", "MultiMediaCard")
                        .WithMany()
                        .HasForeignKey("MultiMediaCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Pcmcia", "PCMCIA")
                        .WithMany()
                        .HasForeignKey("PCMCIAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Scsi", "SCSI")
                        .WithMany()
                        .HasForeignKey("SCSIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.MmcSd", "SecureDigital")
                        .WithMany()
                        .HasForeignKey("SecureDigitalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscImageChef.CommonTypes.Metadata.Usb", "USB")
                        .WithMany()
                        .HasForeignKey("USBId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DiscImageChef.Server.Models.UsbProduct", b =>
                {
                    b.HasOne("DiscImageChef.Server.Models.UsbVendor", "Vendor")
                        .WithMany("Products")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
